/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.lists;

import java.util.Date;
import java.util.concurrent.ConcurrentHashMap;

import javax.swing.JFrame;
import javax.swing.JRadioButton;

import databaseObjects.beans.PersonMVC.DoctorModel;
import databaseObjects.beans.PersonMVC.NurseModel;
import databaseObjects.beans.PersonMVC.PatientModel;
import databaseObjects.beans.PersonMVC.PersonController;
import Views.Login;
import Views.PopUp;
import Views.Home.DoctorHome;
import Views.Home.NurseHome;
import Views.Home.PatientHome;
import Views.forms.NurseForm;
import Views.forms.PatientForm;

/**
 *
 * @author xuelixiao
 */
public class PatientList extends javax.swing.JFrame {
	private PersonController personController;
	private DoctorModel doctor = null;
	private NurseModel nurse = null;
	private ConcurrentHashMap<String, PatientModel> patients = null;
	private ConcurrentHashMap<String, JRadioButton> patientList;
	private JFrame current;
	
	/**
     * Creates new form AllPatients
     */
    public PatientList(PersonController personController) {
    	this.personController = personController;
    	doctor = personController.getDoctor();
    	nurse = personController.getNurse();
    	patients = personController.getListOfPatients();
    	patientList = new ConcurrentHashMap<String, JRadioButton>();
        initComponents();
        current = this;
    }
    /**
     * Creates new form AllPatients
     */
    public PatientList() {
        initComponents();
        current = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel23.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 255));
        jLabel23.setText("Patients");

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        
        if (personController != null) {
        	
        	String[] patientNames = patients.keySet().toArray(new String[patients.size()]);
        	for (int i = 0; i<patientNames.length; i++) {
        		JRadioButton patientButton = new JRadioButton();
        		patientButton.setText(patientNames[i]);
        		patientButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    	if (patientButton.isSelected()) {
                    		String[] currentButtons = patientList.keySet().toArray(new String[patientList.size()]);
                    		for(int j= 0; j<currentButtons.length; j++){
                    			if (!patientButton.getText().equalsIgnoreCase(patientList.get(currentButtons[j]).getText())
                    					&& patientList.get(currentButtons[j]).isSelected()) {
                    				patientList.get(currentButtons[j]).setSelected(false);
                    			}
                    		}
                    	}
                    }
                });
        		patientList.put(patientNames[i], patientButton);
        		
        		jPanel4.add(patientButton);
        	}
        	
        	jButton1.setText("Log out");
        	jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    new Login().setVisible(true);
                }
            });
        	jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    personController.back(current).setVisible(true);;
                }
            });
        	jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    personController.addToPrevious(current);
                    if (doctor != null) new DoctorHome(personController).setVisible(true);
                    else new NurseHome(personController).setVisible(true);
                }
            });
        	
        	// add
        	jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                	personController.addToPrevious(current);
                	PopUp showNurse = new PopUp();
                	if (nurse == null ) {
                		new NurseLists(personController).setVisible(true);
                		showNurse.setText("No nurse currently selected. Redirecting to list of nurses");
                	} else {
                		new PatientForm(personController).setVisible(true);
                		showNurse.setText("Patient will be added to "+nurse.getFirst_name()+" "+nurse.getLast_name());
                	}
                	showNurse.setVisible(true);
                }
            });

        	// update
        	jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                	String[] currentButtons = patientList.keySet().toArray(new String[patientList.size()]);
            		for(int j= 0; j<currentButtons.length; j++) {
            			JRadioButton currentSelection = patientList.get(currentButtons[j]);
            			if (currentSelection.isSelected()) {
            				personController.setNurse(currentSelection.getText());
            				personController.addToPrevious(current);
                        	new PatientForm(personController).setVisible(true);
            				return;
            			}
            			
            			if (j == currentButtons.length - 1) {
            				PopUp noNurseSelected = new PopUp();
            				noNurseSelected.setText("Please Select the patient you wish to update.");
            				noNurseSelected.setVisible(true);
            			}
            			 
            		}
                }
            });

        	// remove
        	jButton7.addActionListener(new java.awt.event.ActionListener() {
        		public void actionPerformed(java.awt.event.ActionEvent evt) {
        			try {
	                	String[] currentButtons = patientList.keySet().toArray(new String[patientList.size()]);
	            		for(int j= 0; j<currentButtons.length; j++) {
	            			JRadioButton currentSelection = patientList.get(currentButtons[j]);
	            			if (currentSelection.isSelected()) {
	            				personController.setNurse(currentSelection.getText());
	            				personController.removePatient();
	            				personController.setDoctorPatients();
	                        	new PatientList(personController).setVisible(true);
	                        	dispose();
	            				return;
	            			}
	            			
	            			if (j == currentButtons.length - 1) {
	            				PopUp noNurseSelected = new PopUp();
	            				noNurseSelected.setText("Please Select the patient you wish to remove.");
	            				noNurseSelected.setVisible(true);
	            			}
	            		}
        			} catch(Exception e) {
                		PopUp noNurseSelected = new PopUp();
        				noNurseSelected.setText(e.getMessage());
        				noNurseSelected.setVisible(true);
                	}
                }
            });

        	// view
        	jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                	String[] currentButtons = patientList.keySet().toArray(new String[patientList.size()]);
            		for(int j= 0; j<currentButtons.length; j++) {
            			JRadioButton currentSelection = patientList.get(currentButtons[j]);
            			if (currentSelection.isSelected()) {
            				personController.setNurse(currentSelection.getText());
            				personController.addToPrevious(current);
                        	new PatientHome(personController).setVisible(true);
            				return;
            			}
            			
            			if (j == currentButtons.length - 1) {
            				PopUp noNurseSelected = new PopUp();
            				noNurseSelected.setText("Please Select the patient you wish to view.");
            				noNurseSelected.setVisible(true);
            			}
            			 
            		}
                }
            });
        	jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                }
            });
        	jButton10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                	personController.forward(current).setVisible(true);
                }
            });
        } else {
        	jButton1.setText(new Date().toString());
        	jRadioButton1.setText("patient1");
            jPanel4.add(jRadioButton1);
        }
        

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/leftArrow.png"))); // NOI18N
        

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/home.png"))); // NOI18N
        

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/search.png"))); // NOI18N


        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/rightArrow.png"))); // NOI18N
        

        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setText("Add");
        jPanel2.add(jButton5);

        jButton6.setText("Update");
        jPanel2.add(jButton6);

        jButton7.setText("Remove");
        jPanel2.add(jButton7);

        jButton8.setText("View");
        jPanel2.add(jButton8);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
